# Generated by Django 5.0.2 on 2024-02-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ['-id']},
        ),
    ]
