# Generated by Django 5.0.2 on 2024-02-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
        ('member', '0002_alter_member_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Latter',
            new_name='Letter',
        ),
        migrations.RenameField(
            model_name='letter',
            old_name='latter_content',
            new_name='letter_content',
        ),
        migrations.AlterModelTable(
            name='letter',
            table='tbl_letter',
        ),
    ]
