# Generated by Django 5.0.2 on 2024-02-28 19:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0003_alter_clubmember_status'),
        ('member', '0001_initial'),
        ('teenplay_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_title', models.TextField()),
                ('post_content', models.TextField()),
                ('image_path', models.ImageField(upload_to='club_post/%Y/%m/%d')),
                ('view_count', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teenplay_server.category')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='club.club')),
            ],
            options={
                'db_table': 'tbl_club_post',
            },
        ),
        migrations.CreateModel(
            name='ClubPostReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reply_content', models.TextField()),
                ('status', models.BooleanField(default=1)),
                ('club_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='club_post.clubpost')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member')),
            ],
            options={
                'db_table': 'tbl_club_post_reply',
            },
        ),
    ]
