# Generated by Django 5.0.2 on 2024-02-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teenplay',
            name='thumbnail_path',
            field=models.ImageField(upload_to='teenplay_thumbnail/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='teenplay',
            name='video_path',
            field=models.ImageField(upload_to='teenplay_video/%Y/%m/%d'),
        ),
    ]
