# Generated by Django 5.0.2 on 2024-02-26 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='tbl_member',
        ),
    ]
