# Generated by Django 5.0.2 on 2024-02-26 20:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club_post', '0001_initial'),
        ('member', '0002_alter_member_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPostReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reply_content', models.TextField()),
                ('status', models.BooleanField(default=1)),
                ('club_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='club_post.clubpost')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member')),
            ],
            options={
                'db_table': 'tbl_club_post_reply',
            },
        ),
    ]
