# Generated by Django 5.0.2 on 2024-02-26 20:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('club', '0001_initial'),
        ('festival', '0001_initial'),
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity_title', models.TextField()),
                ('activity_content', models.TextField()),
                ('recruit_start', models.DateTimeField()),
                ('recruit_end', models.DateTimeField()),
                ('activity_intro', models.TextField()),
                ('activity_address_location', models.TextField()),
                ('activity_address_detail', models.TextField()),
                ('thumbnail_stored_name', models.TextField()),
                ('thumbnail_path', models.TextField()),
                ('activity_start', models.DateTimeField()),
                ('activity_end', models.DateTimeField()),
                ('status', models.BooleanField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.category')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='club.club')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='festival.festival')),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pay.pay')),
            ],
            options={
                'db_table': 'tbl_activity',
            },
        ),
    ]
