# Generated by Django 5.0.2 on 2024-02-26 20:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tag_name', models.TextField()),
                ('status', models.BooleanField(default=1)),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wishlist.wishlist')),
            ],
            options={
                'db_table': 'tbl_wishlist_tag',
            },
        ),
    ]
