# Generated by Django 5.0.2 on 2024-02-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_type',
            field=models.SmallIntegerField(choices=[(0, '공지사항'), (1, ' 자주 묻는 질문')]),
        ),
    ]
