# Generated by Django 5.0.2 on 2024-02-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentsearch',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
