# Generated by Django 5.0.2 on 2024-02-29 11:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_alter_clubmember_status'),
        ('member', '0002_memberprofile_remove_member_profile_path'),
        ('teenplay_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '탈퇴'), (1, '가입중'), (-1, '가입대기')], default=-1),
        ),
        migrations.CreateModel(
            name='ClubPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_title', models.TextField()),
                ('post_content', models.TextField()),
                ('image_path', models.ImageField(upload_to='club_post/%Y/%m/%d')),
                ('view_count', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teenplay_server.category')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='club.club')),
            ],
            options={
                'db_table': 'tbl_club_post',
            },
        ),
        migrations.CreateModel(
            name='ClubPostReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reply_content', models.TextField()),
                ('status', models.BooleanField(default=1)),
                ('club_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='club.clubpost')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member')),
            ],
            options={
                'db_table': 'tbl_club_post_reply',
            },
        ),
    ]
