# Generated by Django 5.0.2 on 2024-02-26 20:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        ('member', '0002_alter_member_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(choices=[(-1, '참가대기'), (0, '취소'), (1, '참가중')], default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.activity')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member')),
            ],
            options={
                'db_table': 'tbl_activity_member',
            },
        ),
    ]
